hunt/forms.py
#coding=utf-8


from flaskext.wtf import Form, TextField, SubmitField, PasswordField, RadioField, \
     SelectMultipleField, SelectField, HiddenField, DateField, IntegerField, \
     validators, required, equal_to, email



class LoginForm(Form):
    email = TextField(u'登录邮箱', validators=[required(message=u'必填'),
                                               email(message=u'不是有效的邮箱地址') ])
    password = PasswordField(u'密码', validators=[required(message=u'必填')])
    next = HiddenField()


class RegisterForm(Form):
    email = TextField(u'登录邮箱', validators=[required(message=u'必填'),
                                               email(message=u'不是有效的邮箱地址') ])
    password = PasswordField(u'密码', validators=[required(message=u'必填')])
    confirm_password = PasswordField(u'确认密码', validators=[equal_to('password', message=u'密码不一致'),
                                                              required(message=u'必填')])

    agree_term = TextField(u'条款确认', validators=[required(message=u'必选')])
    # agree_term = SelectMultipleField(u'条款确认', validators=[required(message=u'必选')])


#### User profile edit ####
class GeneralInfoForm(Form):
    realname = TextField(u'姓名', validators=[required(message=u'必填')])
    sex = HiddenField(u'性别', validators=[required(message=u'必选')]) #, value='1')
    birthday = HiddenField(validators=[required(message=u'必填')]) #, value='1990-10-21')
    current_address = HiddenField(u'当前居住地址', validators=[required(message=u'必填')]) #, value='浙江,杭州')
    account_address = HiddenField(u'户口所在地址', validators=[required(message=u'必填')]) #, value='浙江,台州')
    phone_num = IntegerField(u'', validators=[required(message=u'必填')])
    

class EducationForm(Form):
    degree = TextField(u'学历', validators=[required(message=u'必填')])
    study_date = HiddenField(validators=[required(message=u'必填')])
    school = TextField(u'学校', validators=[required(message=u'必填')])
    speciality_type = HiddenField(u'专业类别', validators=[required(message=u'必填')])
    speciality = TextField(u'专业名称')
    
    

class ItSkillForm(Form):
    it_skills = HiddenField(u'IT技能', validators=[required(message=u'必填')])


#### [end] User profile edit #### 

hunt/__init__.py
from flask import Flask

from hunt.extensions import db
from hunt.views import frontend, account, job


DEFAULT_APP_NAME = 'hunt'

DEFAULT_MODULES = (
    (frontend, ''),
    (account, '/account'),
    (job, '/job'),
)


def create_app(configure=None, modules=None):
    if modules is None:
        modules = DEFAULT_MODULES

    app = Flask(DEFAULT_APP_NAME)
    app.config.from_pyfile(configure)

    configure_extensions(app)
    configure_modules(app, modules)
    return app



def configure_extensions(app):
    db.init_app(app)


def configure_modules(app, modules):
    
    for module, url_prefix in modules:
        app.register_blueprint(module, url_prefix=url_prefix)

hunt/scripts/__init__.py
#coding=utf-8

hunt/views/__init__.py
from .frontend import frontend
from .account import account
from .job import job

hunt/views/account.py
#coding=utf-8

from datetime import datetime
import json

from flask import Blueprint, request, render_template, redirect, url_for, flash, \
     session
from sqlalchemy.exc import IntegrityError

from hunt.extensions import db
from hunt.forms import RegisterForm, LoginForm, GeneralInfoForm, EducationForm, ItSkillForm
from hunt.models import User


account = Blueprint('account', __name__)

#### Account ####
@account.route('/login/', methods=('GET', 'POST'))
def login():
    
    form = LoginForm(next=request.args.get('next', ''))
    if request.method == 'POST':
        if form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            user = User.query.filter(db.and_(User.email==email,
                                             User.password==password)).first()
            if user:
                session['uid'] = user.id
                user.lastlogin = datetime.now()
                db.session.commit()
                next = form.next.data
                next = next if next else url_for('frontend.index')
                return redirect(next)
            else:
                flash(u'邮箱地址或密码错误!')
        else:
            print form.errors

    return render_template('login.html', form=form)


@account.route('/logout/')
def logout():
    if session.get('uid'):
        session.pop('uid')
    return redirect(url_for('frontend.index'))


@account.route('/register/', methods=('GET', 'POST'))
def register():

    form = RegisterForm()
    
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User()
            form.populate_obj(user)
            db.session.add(user)
            try:
                db.session.commit()
                return redirect(url_for('account.login'))
            except IntegrityError:
                db.session.rollback()
                flash(u'该邮箱已被注册!')
        else:
            print form.errors
    
    return render_template('register.html', form=form)



@account.route('/profile/edit/', methods=('GET', 'POST'))
def user_profile_edit():
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login', next=url_for('account.user_profile_edit')))

    user = User.query.get(uid)
    gi_form = GeneralInfoForm()
    edu_form = EducationForm()
    itskill_form = ItSkillForm()

    return render_template('user-profile-edit.html', user=user,
                           gi_form=gi_form, edu_form=edu_form, itskill_form=itskill_form)



@account.route('/update/generalinfo/', methods=('POST',))
def update_general_info():
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login', next=url_for('account.user_profile_edit')))

    form = GeneralInfoForm()

    user = User.query.get(uid)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        return json.dumps({'success' : True, 'message' : u'更新成功!'})
    else:
        print form.errors
        form.errors['success'] = False
        form.errors['message'] = u'更新失败!'
        return json.dumps(form.errors)


@account.route('/update/educationinfo/', methods=('POST',))
def update_education_info():
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login', next=url_for('account.user_profile_edit')))
    
    user = User.query.get(uid)
    form = EducationForm()
    if form.validate_on_submit():
        form.populate_obj(user)
        user.study_start, user.study_end = form.study_date.data.split(',')
        # print user.study_start, user.study_end
        db.session.add(user)
        db.session.commit()
        return json.dumps({'success' : True, 'message' : u'更新成功!'})
    else:
        print form.errors
        form.errors['success'] = False
        form.errors['message'] = u'更新失败!'
        return json.dumps(form.errors)

            

all_skills = ('Word', 'Excel', 'PowerPoint', 'C#', 'C',
              'C++', 'Java', 'JSP', 'PHP', 'VB',
              'VC++', 'SQLServer', 'Access', 'MySQL', 'Oracle',
              'SPSS', 'HTML', 'JavaScript', 'Linux', 'WINDOWS',
              '3DMAX', 'Flash', 'Premiere', 'Photoshop', 'CorelDraw',
              'Illustrator', 'AutoCAD', 'Pro/E', 'Protel', 'Python' ,
              'Emacs')

@account.route('/update/itskillinfo/', methods=('POST',))
def update_itskill_info():
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login',
                                next=url_for('account.user_profile_edit')))
    
    user = User.query.get(uid)
    form = ItSkillForm()
    if form.validate_on_submit():
        user.it_skills = form.it_skills.data
        db.session.add(user)
        db.session.commit()
        return json.dumps({'success' : True, 'message' : u'更新成功!'})
    else:
        form.errors['success'] = False
        form.errors['message'] = u'更新失败!'
        return json.dumps(form.errors)

hunt/views/frontend.py
from flask import Blueprint, request, render_template, current_app,\
     send_from_directory

frontend = Blueprint('frontend', __name__)



@frontend.route('/')
def index():
    return render_template('layout.html')



@frontend.route('/favicon.ico')
def favicon():
    return send_from_directory(current_app.config['UPLOADS_DEFAULT_DEST'],
                               'images/favicon.ico', as_attachment=False)

hunt/views/job.py
#coding=utf-8

import datetime
import json
from flask import Blueprint, request, session, render_template, url_for, abort, redirect
from hunt.extensions import db
from hunt.models import Job, Company, JobRequest

job = Blueprint('job', __name__)


@job.route('/search/')
@job.route('/search/p/<int:page>/')
def search(page=1):
    if page < 1 : page = 1

    exp = request.args.get('exp', '')
    salary = request.args.get('salary', 0, type=int)
    public_date = request.args.get('public_date', '')
    key_words = request.args.get('key_words' ,'')
    company_name = request.args.get('company_name' ,'')
    work_place = request.args.get('work_place' ,'')

    month_days = (31, 28, 31, 30, 31, 30,
                  31, 31, 30, 31, 30, 31)

    query = Job.query
    if exp and exp != u'不限':
        query = query.filter(Job.exp==exp)
    if salary:
        query = query.filter(Job.salary_low >= salary)
    if public_date and public_date != 'all':
        today = datetime.date.today()
        diff = datetime.timedelta(days=0)
        if public_date == 'month':
            last_month = today.month-2 if today.month>=2 else 11
            diff = datetime.timedelta(days=month_days[last_month])
        elif public_date == 'week':
            diff = datetime.timedelta(days=7)
        elif public_date == '3days':
            diff = datetime.timedelta(days=3)
        elif public_date == 'today':
            pass
        date_start = (today-diff).strftime('%Y-%m-%d')
        query = query.filter(Job.public_date >= date_start)

    if key_words:
        words = key_words.split()
        for word in words:
            query = query.filter(db.or_(Job.description.ilike('%'+ word +'%'),
                                        Job.title.ilike('%'+ word +'%')))
    if company_name:
        query = query.filter(Job.company.has(Company.name.ilike('%' + company_name + '%')))
    if work_place:
        place = work_place.split()
        if len(place) > 0:
            query = query.filter(Job.work_city==place[0])
            if len(place) == 2:
                query = query.filter(Job.work_area==place[1])

    page_url = lambda page: url_for('job.search', page=page,
                                    exp=exp, salary=salary,
                                    public_date=public_date, key_words=key_words,
                                    company_name=company_name, work_place=work_place)
    page_obj = query.paginate(page=page, per_page=20)

    return render_template('job-search.html',
                           page_obj=page_obj, page_url=page_url,
                           exp=exp, salary=salary,
                           public_date=public_date, key_words=key_words,
                           company_name=company_name, work_place=work_place)



@job.route('/view/<int:id>/')
def view(id):
    job = Job.query.get_or_404(id)
    return render_template('job-view.html', job=job)


@job.route('/addRequest/<int:job_id>/')
def addRequest(job_id):
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login',
                                next=url_for('job.addRequest', job_id=job_id)))

    job_request = JobRequest.query.filter(db.and_(JobRequest.user_id==uid,
                                                  JobRequest.job_id==job_id)).first()
    if job_request:
        return json.dumps({'success': False, 'message': u'已申请!'})
    else:
        job_request = JobRequest(user_id=uid, job_id=job_id)
        db.session.add(job_request)
        db.session.commit()
        return json.dumps({'success': True,
                           'from': 'add',
                           'url': url_for('job.delRequest', req_id=job_request.id)})


@job.route('/delRequest/<int:req_id>/')
def delRequest(req_id):
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login'))

    job_request = JobRequest.query.get_or_404(req_id)
    db.session.delete(job_request)
    db.session.commit()
    return json.dumps({'success': True,
                       'from': 'del',
                       'url': url_for('job.addRequest', job_id=job_request.job_id)})


@job.route('/feedback/')
@job.route('/feedback/<int:page>/')
def feedback(page=1):
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login',
                                next=url_for('job.feedback')))
    
    filter_ = request.args.get('filter', '') 
    if page < 1: page = 1
    cnt_total = JobRequest.query.filter(JobRequest.user_id==uid).count()
    cnt_feedbacked = JobRequest.query.filter(db.and_(JobRequest.user_id==uid,
                                                     JobRequest.feedbacked==True)).\
                                                     count()
    cnt_checked = JobRequest.query.filter(db.and_(JobRequest.user_id==uid,
                                                  JobRequest.checked==True)).\
                                                  count()
    query = JobRequest.query.filter(JobRequest.user_id==uid)
    if filter_:
        if filter_ == 'unfeedback':
            query = query.filter(JobRequest.feedbacked==False)
        else:
            query = query.filter(JobRequest.feedbacked==True)
            if filter_ == 'checked':
                query = query.filter(JobRequest.checked==True)
            elif filter_ == 'uncheck':
                query = query.filter(JobRequest.checked==False)

    query = query.order_by(JobRequest.createdate)

    page_url = lambda page: url_for('job.feedback',
                                    page=page,filter=filter_)
    page_obj = query.paginate(page=page, per_page=20)

    return render_template('job-feedback.html',
                           page_obj=page_obj, page_url=page_url,
                           cnt_total=cnt_total, cnt_feedbacked=cnt_feedbacked,
                           cnt_checked=cnt_checked, filter=filter_)


@job.route('/getFeedbackInfo/<int:req_id>/')
def getFeedbackInfo(req_id):
    uid = session.get('uid')
    if not uid:
        return redirect(url_for('account.login'))

    job_request = JobRequest.query.filter(db.and_(JobRequest.id==req_id,
                                                  JobRequest.user_id==uid)).first()
    if not job_request:
        return json.dumps({'success': False,
                           'message': u'此职位请求不存在或不为你所有.'})
    else:
        job_request.checked = True
        db.session.add(job_request)
        db.session.commit()
        return json.dumps({'success': True,
                           'hr_evaluate': job_request.hr_evaluate,
                           'hr_msg': job_request.hr_msg if job_request.hr_msg else ''})


@job.route('/recommend/')
def recommend():
    return render_template('job-recommend.html')

hunt/templates/_forms.html
{% macro render_errors(field) %}
{% if field.errors %}

{% for error in field.errors  %}
<sup class="ym-required">{{ error }}</sup>
{% endfor %}

{% endif %}
{% endmacro %}

hunt/templates/_job-feedback.html
    <section class="ym-grid linearize-level-1">
	<table class="bordertable" style="font-size:0.9em;">
	    <thead>
		<tr>
		    <th width="32%">职位名称</th>
		    <th width="23%">公司名称</th>
		    <th width="11%">工作地点</th>
		    <th width="7%">工作经验</th>
		    <th width="10%">薪资水平</th>
		    <th width="9%">发布日期</th>
		    <th whdth="8%">申请职位</th>
		</tr>
	    </thead>
	    <tbody>
		{% if page_obj.items %}
		{% for job in page_obj.items %}
		<tr>
		    <td>
			<a href="{{ url_for('job.view', id=job.id ) }}" target="_blank">{{ job.title }}</a>
			<!-- <a href="{{ job.zhaopin_url }}">[ 智联招聘的页面 ]</a> -->
		    </td>
		    <td><a href="{{ job.company.zhaopin_url }}">{{ job.company.name }}</a></td>
		    <td>{{ job.work_city }}{% if job.work_area %} - {{ job.work_area }}{% endif %} </td>
		    <td>{{ job.exp }}</td>
		    <td>{% if job.salary_low %}{{ job.salary_low }}-{{ job.salary_high }}{% endif %}</td>
		    <td>{{ job.public_date.strftime('%Y-%m-%d') }}</td>
		    <td><a class="ym-button do-request" style="color:#4D87C7 !important;font-weight:bold;"
			   href="#" url="{{ url_for('job.addRequest', job_id=job.id) }}">申请</a></td>
		</tr>
		{% endfor %}
		{% endif %}
	    </tbody>
	</table>
    </section>
    <section class="ym-grid linearize-level-1">
	<div class="ym-gr" style="padding:10px">
	    {{ pagination(page_obj, page_url) }}
	</div>
    </section>
<div class="tab-content">
    <table class="bordertable">
	<thead>
	    <tr>
		<th>职位名称</th>
		<th>公司名称</th>
		<th>工作地点</th>
		<th>发布日期</th>
		<th></th>
	    </tr>
	</thead>
	<tbody>
	    <tr>
		<td>..</td>
		<td>..</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
	    </tr>
	    <tr>
		<td>..</td>
		<td>..</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
	    </tr>
	</tbody>
    </table>
</div>

hunt/templates/_job-recommend.html
<div class="tab-content">
    <table class="bordertable">
	<thead>
	    <tr>
		<th>职位名称</th>
		<th>公司名称</th>
		<th>工作地点</th>
		<th>发布日期</th>
		<th></th>
	    </tr>
	</thead>
	<tbody>
	    <tr>
		<td>..</td>
		<td>..</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
	    </tr>
	    <tr>
		<td>..</td>
		<td>..</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
	    </tr>
	    <tr>
		<td>..</td>
		<td>..</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
	    </tr>
	</tbody>
    </table>
</div>

hunt/templates/layout.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh" lang="zh">
    <head>
	<title>{% block title %}Home{% endblock %}</title>
	
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<!-- Style Sheet -->
	<link rel="stylesheet" href="/static/yaml/core/base.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/core/iehacks.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/screen/grid-960-12.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/screen/typography.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/screen/screen-FULLPAGE-layout.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/navigation/hlist.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/forms/gray-theme.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/print/print.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/add-ons/microformats/microformats.css" type="text/css" />
	<link rel="stylesheet" href="/static/yaml/add-ons/accessible-tabs/tabs.css" type="text/css" />
	<!-- <link href="http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700|Droid+Sans:700" -->
	<!--       rel="stylesheet" type="text/css"> -->
	<!-- <link rel="stylesheet" href="/static/yaml/add-ons/rtl-support/navigation/hlist-rtl.css" type="text/css" /> -->
	<!-- <link rel="stylesheet" href="/static/yaml/add-ons/rtl-support/core/base-rtl.css" type="text/css" /> -->
	<!-- <link rel="stylesheet" href="/static/yaml/add-ons/rtl-support/screen/typography-rtl.css" type="text/css" /> -->
	
	{% block more_css %}
	{% endblock %}
	
	<!-- javascript -->
	<script type="text/javascript" src="/static/yaml/core/js/yaml-focusfix.js"></script>
	
	<script type="text/javascript" src="/static/js/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.snippet.js"></script>
	<script type="text/javascript" src="/static/js/jquery.gridbuilder.js"></script>
	<script type="text/javascript" src="/static/yaml/add-ons/accessible-tabs/jquery.tabs.js"></script>
	<script type="text/javascript" src="/static/yaml/add-ons/syncheight/jquery.syncheight.js"></script>
	<script type="text/javascript" src="/static/js/domscript.js"></script>
	{% block more_js %}
	{% endblock %}
    </head>
    <body>
	<ul class="ym-skiplinks">
	    <li><a class="ym-skip" href="#nav">Skip to navigation (Press Enter)</a></li>
	    <li><a class="ym-skip" href="#main">Skip to main content (Press Enter)</a></li>
	</ul>
	
	<header style="background: #161E21;text-shadow:1px 1px 1px rgba(0, 0, 0, .8);">
	    <div class="ym-wrapper">
		<div class="ym-wbox">
		    <h2 style="color: #8B8F90;font-family:Microsoft Yahei;">个人求职</h2>
		</div>
	    </div>
	</header>
	<nav id="nav" style="border-top: 1px black solid; background: #080B0C;">
	    <div class="ym-wrapper">
		<div class="ym-hlist" style="border-top: 1px black solid; background: #080B0C;">
		    <ul class="ym-gl">
			{% set uid = session.get('uid') if session.get('uid') else False %}
			{% set current_url = request.environ.PATH_INFO %}
			<li {% if current_url==url_for('frontend.index') %} class="active" {% endif %}>
			    <a href="{{url_for('frontend.index')}}" >首页</a></li>
			
			<li {% if current_url==url_for('job.search') %} class="active" {% endif %}>
			    <a href="{{url_for('job.search')}}">职位搜索</a></li>
			
			{% if current_url==url_for('job.view', id=1) %}
			<li class="active" > <a href="{{url_for('job.view', id=1)}}">职位详情</a></li>
			{% endif %}
			
			{% if uid %}
			<li {% if current_url==url_for('job.feedback') %} class="active" {% endif %}>
			    <a href="{{url_for('job.feedback')}}">求职反馈</a></li>
			
			<!-- <li {% if current_url==url_for('job.recommend') %} class="active" {% endif %}> -->
			<!--     <a href="{{url_for('job.recommend')}}">职位推荐</a></li> -->
			{% endif %}
		    </ul>
		    <!-- <form class="ym-searchform"> -->
		    <!-- 	<input class="ym-searchfield" type="search" placeholder="Search..." /> -->
		    <!-- 	<input class="ym-searchbutton" type="submit" value="Search" /> -->
		    <!-- </form> -->
		    <div class="ym-gr">
			<ul>
			    {% if uid %}
			    <li {% if current_url==url_for('account.user_profile_edit') %} class="active" {% endif %}>
				<a href="{{url_for('account.user_profile_edit')}}">完善用户资料</a></li>

			    <li {% if current_url==url_for('account.logout') %} class="active" {% endif %}>
				<a href="{{url_for('account.logout')}}">退出</a></li>
			    {% else %}

			    <li {% if current_url==url_for('account.login') %} class="active" {% endif %}>
				<a href="{{url_for('account.login')}}">登录</a></li>
			    
			    <li {% if current_url==url_for('account.register') %} class="active" {% endif %}>
				<a href="{{url_for('account.register')}}">注册</a></li>
			    {% endif %}
			</ul>
		    </div>
		</div>
	    </div>
	</nav>
	<div id="main" style="min-height:459px;">
	    <div class="ym-wrapper">
		{% block wbox %}
		<div class="ym-wbox">
		    <!-- 搜索框 -->
		    <section class="ym-grid linearize-level-1">
			<div class="box info">
			    <h4>职位搜索</h4>
			    <form method="get" action="{{url_for('job.search')}}"
				  id="demo-form2" class="ym-form linearize-form ym-full" role="application">
				<div class="ym-grid linearize-level-1">
				    <div class="ym-g80 ym-gl">
					<div class="ym-grid linearize-level-2">
					    <div class="ym-g33 ym-gl">
						<div class="ym-gbox ym-fbox-select">
						    <label for="exp">工作经验</label>
						    <select name="exp" id="exp" size="1" style="width:auto;">
							<!-- <option value="0" selected="selected" disabled="disabled">请选择</option> -->
							<option value="不限">不限</option>
							<option value="无经验">无经验</option>
							<option value="1年以下">1年以下</option>
							<option value="1-2年">1-2年</option>
							<option value="1-3年">1-3年</option>
							<option value="1-5年">1-5年</option>
							<option value="1-6年">1-6年</option>
							<option value="1-8年">1-8年</option>
							<option value="1-10年">1-10年</option>
							<option value="3-5年">3-5年</option>
							<option value="2-3年">2-3年</option>
							<option value="2-4年">2-4年</option>
							<option value="2-5年">2-5年</option>
							<option value="2-7年">2-7年</option>
							<option value="2-10年">2-10年</option>
							<option value="3-10年">3-10年</option>
							<option value="5-10年">5-10年</option>
							<option value="1年以上">1年以上</option>
							<option value="2年以上">2年以上</option>
							<option value="3年以上">3年以上</option>
							<option value="4年以上">4年以上</option>
							<option value="5年以上">5年以上</option>
							<option value="7年以上">7年以上</option>
							<option value="8年以上">8年以上</option>
							<option value="10年以上">10年以上</option>
						    </select>
						</div>
						<div class="ym-gbox ym-fbox-select">
						    <label for="salary">薪资水平</label>
						    <select name="salary" id="salary" style="width:auto;">
							<option value="0">不限</option>
							<option value="1000">1000+</option>
							<option value="1500">1500+</option>
							<option value="2000">2000+</option>
							<option value="3000">3000+</option>
							<option value="4000">4000+</option>
							<option value="5000">5000+</option>
							<option value="6000">6000+</option>
							<option value="8000">8000+</option>
							<option value="10000">10000+</option>
							<option value="15000">15000+</option>
						    </select>
						</div>
					    </div>
					    <div class="ym-g33 ym-gl">
						<div class="ym-gbox ym-fbox-select">
						    <label for="public-date">发布日期</label>
						    <select name="public_date" id="public-date" style="width:auto;" >
							<option value="all" selected="selected">所有日期</option>
							<option value="month">最近一个月</option>
							<option value="week">最近一周</option>
							<option value="3days">最近3天</option>
							<option value="today">今天</option>
						    </select>
						    <!-- <label style="width:10px;float:left;">&nbsp;</label> -->
						</div>
						<div class="ym-gbox ym-fbox-text">
						    <label for="key-word">关键词</label>
						    <input type="text" name="key_words" value="{{ key_words }}"
							   id="key-word" size="20" placeholder="与招聘内容相关">
						</div>
					    </div>
					    <div class="ym-g33 ym-gl">
						<div class="ym-gbox ym-fbox-text">
						    <label for="company-name">公司名称</label>
						    <input type="text" name="company_name" value="{{ company_name }}" id="company-name" size="20">
						</div>
						<div class="ym-gbox ym-fbox-text">
						    <label for="work-place">工作地点</label>
						    <input type="text" name="work_place" value="{{ work_place }}"
							   id="work-place" size="20" placeholder="例如(浙江 杭州)">
						</div>
					    </div>
					</div>
				    </div>
				    
				    <div class="ym-g20 ym-gr">
					<div class="ym-fbox-button">
					    <input type="submit" value="搜索" class="submit" id="submit1">
					    <input type="reset" value="重置" class="reset" id="reset1" name="reset1">
					</div>
				    </div>
				</div>
			    </form>
			</div>
		    </section>
		    
		    <section class="box">
			<div class="">
			    <a href="http://www.google.com/">
			    </a>
			</div>
		    </section>
		</div>
		{% endblock %}
	    </div>
	</div>
	<footer style="background: #161E21;text-shadow:1px 1px 1px rgba(0, 0, 0, .8);border-top: 2px black solid;">
	    <div class="ym-wrapper">
		<div class="ym-wbox">
		    <p>© weet-DT 2012 &ndash; Layout based on <a href="http://www.yaml.de">YAML</a></p>
		</div>
	    </div>
	</footer>
	
    </body>
</html>